import = [
    "~/.config/alacritty/theme.toml",
    "~/.config/alacritty/font.toml",
    "~/dotfiles/defaults/alacritty.toml"
]

[window]
opacity = 0.95
padding.x = 0
padding.y = 0
dimensions.columns = 100
dimensions.lines = 85

[font]
size = 12